name: jal_raksha
description: "Jal Raksha"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  material_charts: ^0.0.34
  maplibre_gl: ^0.22.0
  geolocator: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
